spring:
  application:
    name: oauth2
server:
  port: 9522
  servlet:
    context-path: /${spring.application.name}
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
logging:
  config: classpath:logback-spring.xml

