gtop:
  messages:
    application-message-map:
      1100: "用户名/密码错误，请重新输入！"
      1101: "该用户已被停用！"
      1102: "用户未登陆！"
      1104: "请先登录！"
      1105: "当前配置不支持此接口"
      1106: "系统异常！异常信息：{0}"
      1107: "系统异常！"
      1108: "用户名：{}存在多个或不存在！"
      1109: "用户手机号：{}存在多个或不存在！"
      1110: "用户切换部门成功！"
      1111: "获取用户站点列表成功！"
      1112: "ClientId/Secret错误，请仔细核对！"
