spring:
  datasource:
    url: jdbc:mysql://10.12.107.80:3306/tc_test?characterEncoding=utf8&useSSL=false
    username: root
    password: Cci@2020
  redis:
    host: 10.12.107.80
    port: 7379
    password: GzTeam628#Cci2018